Repository callsmusic/remix, pull requests merged in 2022-01, with the labels that each got.

#67 Lyrics
  README.md
  locales/en.json
  package-lock.json
  package.json
  src/bot/handlers/index.ts
  src/bot/handlers/lyrics.ts
Labels: enhancement

#68 Fix problems with long lyrics
  package-lock.json
  package.json
  src/bot/handlers/lyrics.ts
  src/bot/helpers/text.ts
Labels: bug

#69 Readme: Heroku deployment
  README.md
Labels: documentation

#75 Rework Central Kurdish
  locales/ckb.ftl
Labels: translations

#74 Migrate internationalization to Fluent
  locales/bn.json
  locales/ckb.ftl
  locales/ckb.json
  locales/de.json
  locales/en.ftl
  locales/en.json
  locales/es.json
  locales/fa.json
  locales/id.json
  locales/ml.json
  locales/pt_BR.json
  locales/si.json
  locales/tr.json
  package-lock.json
  package.json
  src/bot/context.ts
  src/bot/errors.ts
  src/bot/fluent.ts
  src/bot/handlers/cache.ts
  src/bot/handlers/chat_member_updated.ts
  src/bot/handlers/controls.ts
  src/bot/handlers/lyrics.ts
  src/bot/handlers/now.ts
  src/bot/handlers/panel.ts
  src/bot/handlers/playlist.ts
  src/bot/handlers/search.ts
  src/bot/handlers/stream.ts
  src/bot/i18n.ts
  src/bot/index.ts
  src/bot/streamer/audio.ts
  src/bot/streamer/custom.ts
Labels: feat, breaking

#83 Added de lang
  .github/README.md
  locales/de.ftl
Labels: translations
